name: Node.js CI

on:
  push:
    branches: 
      - main
    paths:
      - "app/**"
      - "docker-compose.yml"
      - ".github/workflows/nodejs.yml"

    permissions:
      contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: checking docker ps 
        run: docker ps

      - name: stopping the previous containers
        run: docker compose down

      - name: start server
        run: docker compose up --build -d

      - name: checking the containers
        run: docker ps
      

